source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
use_frameworks!

#pod 'Former'
pod 'AFNetworking', '2.6.3'
pod 'iCarousel'
pod 'MBProgressHUD', '~> 0.8'
pod 'MMDrawerController', '~> 0.5.7'
pod 'Parse'
pod 'ParseUI'
pod 'FBSDKCoreKit', '~> 4.8'
pod 'ParseFacebookUtilsV4', '1.8.5'
#pod 'ParseFacebookUtils'
pod 'NMRangeSlider'
#pod 'Eureka'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'ActionSheetPicker-3.0', '~> 2.0.4'
pod 'TTRangeSlider'
#pod 'MisterFusion'
pod 'BMASliders'
#pod 'MARKRangeSlider'

#bolts-ios #reactivecocoa mvvm
#objectivesugar
link_with 'Simbi', 'SimbiTests'
