source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

pod 'AFNetworking'
pod 'iCarousel', '~> 1.7.6'
pod 'MBProgressHUD', '~> 0.8'
pod 'MMDrawerController', '~> 0.5.7'
pod 'Parse'
pod 'ParseUI'
pod 'FBSDKCoreKit', '~> 4.7'
pod 'ParseFacebookUtilsV4', '~> 1.9'
pod 'NMRangeSlider', '~> 1.2.1'

link_with 'Simbi', 'SimbiTests'
